CREATE TABLE [dbo].[IsiDataWholesale] (
    [isiDataWholesaleId]              INT              IDENTITY (1, 1) NOT NULL,
    [isiFileJobId]                    INT              NOT NULL,
    [investorId]                      INT              NULL,
    [investorName]                    NVARCHAR (1200)  NULL,
    [isPIE]                           CHAR (1)         NULL,
    [fundId]                          INT              NULL,
    [fundName]                        NVARCHAR (400)   NULL,
    [fundValuationDate]               DATE             NULL,
    [currency]                        VARCHAR (3)      NULL,
    [totalUnitsOnIssue]               DECIMAL (38, 10) NULL,
    [investorUnitsHeld]               DECIMAL (38, 10) NULL,
    [basePrice]                       DECIMAL (38, 10) NULL,
    [entryPrice]                      DECIMAL (38, 10) NULL,
    [exitPrice]                       DECIMAL (38, 10) NULL,
    [taxableIncome]                   DECIMAL (38, 10) NULL,
    [nonTaxableIncome]                DECIMAL (38, 10) NULL,
    [foreignTaxCredits]               DECIMAL (38, 10) NULL,
    [dividendWithholdingPayments]     DECIMAL (38, 10) NULL,
    [residentWithholdingTax]          DECIMAL (38, 10) NULL,
    [imputationCredits]               DECIMAL (38, 10) NULL,
    [formationLossesUsed]             DECIMAL (38, 10) NULL,
    [landLossesUsed]                  DECIMAL (38, 10) NULL,
    [deductibleExpenses]              DECIMAL (38, 10) NULL,
    [investorAccountRebates]          DECIMAL (38, 10) NULL,
    [investorAccountExpenses]         DECIMAL (38, 10) NULL,
    [cpu_TaxableIncome]               DECIMAL (38, 10) NULL,
    [cpu_NonTaxableIncome]            DECIMAL (38, 10) NULL,
    [cpu_ForeignTaxCredits]           DECIMAL (38, 10) NULL,
    [cpu_DividendWithholdingPayments] DECIMAL (38, 10) NULL,
    [cpu_ResidentWithholdingTax]      DECIMAL (38, 10) NULL,
    [cpu_ImputationCredits]           DECIMAL (38, 10) NULL,
    [cpu_FormationLossesUsed]         DECIMAL (38, 10) NULL,
    [cpu_LandLossesUsed]              DECIMAL (38, 10) NULL,
    [cpu_DeductibleExpenses]          DECIMAL (38, 10) NULL,
    [cpu_InvestorAccountRebates]      DECIMAL (38, 10) NULL,
    [cpu_InvestorAccountExpenses]     DECIMAL (38, 10) NULL,
    [folderName]                      VARCHAR (120)    NULL,
    CONSTRAINT [PK_IsiDataWholesale] PRIMARY KEY CLUSTERED ([isiDataWholesaleId] ASC),
    CONSTRAINT [FK_IsiDataWholesale_IsiDataWholesale] FOREIGN KEY ([isiDataWholesaleId]) REFERENCES [dbo].[IsiDataWholesale] ([isiDataWholesaleId]),
    CONSTRAINT [FK_IsiDataWholesale_IsiFileJob] FOREIGN KEY ([isiFileJobId]) REFERENCES [dbo].[IsiFileJob] ([isiFileJobId])
);

