CREATE TABLE [dbo].[MemberTax] (
    [id]                              INT             IDENTITY (1, 1) NOT NULL,
    [addedDate]                       DATETIME        CONSTRAINT [DF_Tax_addedDate] DEFAULT (getdate()) NULL,
    [memberid]                        INT             NULL,
    [pieId]                           INT             NULL,
    [valuationDate]                   SMALLDATETIME   NULL,
    [PIR]                             FLOAT (53)      NULL,
    [cashAccountInterest]             DECIMAL (18, 2) NOT NULL,
    [investedTaxableIncome]           FLOAT (53)      NULL,
    [investedTaxableIncomeAdjustment] FLOAT (53)      CONSTRAINT [DF_Tax_taxableAmountAdjustment] DEFAULT ((0)) NULL,
    [FDR]                             FLOAT (53)      CONSTRAINT [DF_Tax_FDR] DEFAULT ((0)) NULL,
    [adjustmentFDR]                   FLOAT (53)      CONSTRAINT [DF_Tax_fdrAdjustment] DEFAULT ((0)) NULL,
    [tolAmount]                       DECIMAL (18, 2) NULL,
    [fee]                             DECIMAL (18, 2) NULL,
    [taxableAmount]                   FLOAT (53)      NULL,
    [FTC]                             FLOAT (53)      NULL,
    [IC]                              FLOAT (53)      NULL,
    [DWP]                             FLOAT (53)      NULL,
    [RWT]                             FLOAT (53)      NULL,
    [adjustmentFTC]                   FLOAT (53)      NULL,
    [adjustmentIC]                    FLOAT (53)      NULL,
    [adjustmentDWP]                   FLOAT (53)      NULL,
    [adjustmentRWT]                   FLOAT (53)      NULL,
    [openingTaxableAmount]            FLOAT (53)      NULL,
    [openingFTC]                      FLOAT (53)      NULL,
    [openingIC]                       FLOAT (53)      NULL,
    [openingDWP]                      FLOAT (53)      NULL,
    [openingRWT]                      FLOAT (53)      NULL,
    [closingTaxableAmount]            FLOAT (53)      NULL,
    [closingFTC]                      FLOAT (53)      NULL,
    [closingIC]                       FLOAT (53)      NULL,
    [closingDWP]                      FLOAT (53)      NULL,
    [closingRWT]                      FLOAT (53)      NULL,
    [taxPayable]                      DECIMAL (18, 2) CONSTRAINT [DF_Tax_taxPayable] DEFAULT ((0)) NULL,
    [taxPaidDate]                     SMALLDATETIME   NULL,
    [leftOverFTC]                     FLOAT (53)      CONSTRAINT [DF_Tax_leftOverFTC] DEFAULT ((0)) NULL,
    [fdrLiability]                    FLOAT (53)      CONSTRAINT [DF_Tax_fdrLiabity] DEFAULT ((0)) NULL,
    [fdrLiabilityPayable]             DECIMAL (18, 2) CONSTRAINT [DF_Tax_fdrLiabilityPayable] DEFAULT ((0)) NULL,
    [oldFdrLiabilityPayable]          DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_Tax] PRIMARY KEY CLUSTERED ([id] ASC)
);

