CREATE TABLE [dbo].[ReportAnnualIR854InvestorCertificate] (
    [id]                                         INT             IDENTITY (1, 1) NOT NULL,
    [memberid]                                   INT             NULL,
    [pieId]                                      INT             NULL,
    [versionNumber]                              NVARCHAR (8)    NULL,
    [periodEndDate]                              SMALLDATETIME   NULL,
    [InvestorName]                               NVARCHAR (200)  NULL,
    [InvestorIrdNumber]                          INT             NULL,
    [PIRAtYearEnd]                               DECIMAL (18, 2) NULL,
    [PIRChangedDuringTheYear]                    NVARCHAR (100)  NULL,
    [taxableIncomeOrLoss]                        DECIMAL (18, 2) NULL,
    [taxCredits]                                 DECIMAL (18, 2) NULL,
    [taxPaid]                                    DECIMAL (18, 2) NULL,
    [taxableIncomeOrLossLowPIR]                  DECIMAL (18, 2) NULL,
    [taxCreditsLowPIR]                           DECIMAL (18, 2) NULL,
    [taxPaidLowPIR]                              DECIMAL (18, 2) NULL,
    [taxableIncomeOrLossZeroRated]               DECIMAL (18, 2) CONSTRAINT [DF_TaxInvestorCertificates_ZeroRatedExitedInvestorTaxableIncOrLoss] DEFAULT ((0)) NULL,
    [TotalZeroRatedAllocatedFTCr]                DECIMAL (18, 2) CONSTRAINT [DF_TaxInvestorCertificates_TotalZeroRatedAllocatedFTCr] DEFAULT ((0)) NULL,
    [TotalZeroRatedAllocatedDWPMATaxCr]          DECIMAL (18, 2) CONSTRAINT [DF_TaxInvestorCertificates_TotalZeroRatedAllocatedDWPMATaxCr] DEFAULT ((0)) NULL,
    [TotalZeroRatedAllocatedICTaxCr]             DECIMAL (18, 2) CONSTRAINT [DF_TaxInvestorCertificates_TotalZeroRatedAllocatedICTaxCr] DEFAULT ((0)) NULL,
    [TotalZeroRatedAllocatedRWTTaxCr]            DECIMAL (18, 2) CONSTRAINT [DF_TaxInvestorCertificates_TotalZeroRatedAllocatedRWTTaxCr] DEFAULT ((0)) NULL,
    [ZeroRatedExitedInvestorTaxPayForExitPeriod] DECIMAL (18, 2) CONSTRAINT [DF_TaxInvestorCertificates_ZeroRatedExitedInvestorTaxPayForExitPeriod] DEFAULT ((0)) NULL,
    [addedDate]                                  DATETIME        CONSTRAINT [DF_TaxInvestorCertificates_addedDate] DEFAULT (getdate()) NULL,
    [isAccountClosed]                            BIT             NULL,
    [accountClosedDate]                          DATETIME        NULL,
    [dob]                                        SMALLDATETIME   NULL,
    [contactAddress]                             NVARCHAR (200)  NULL,
    [countryCode]                                NVARCHAR (20)   NULL,
    [emailAddress]                               NVARCHAR (100)  NULL,
    [phoneNumber]                                NVARCHAR (50)   NULL,
    [homeCountryTaxFile]                         NVARCHAR (20)   NULL,
    [unitsHeldAtYearEnd]                         DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_TaxInvestorCertificates] PRIMARY KEY CLUSTERED ([id] ASC)
);

