CREATE TABLE [dbo].[TaxQuarterSummary] (
    [id]                            INT             IDENTITY (1, 1) NOT NULL,
    [addedDate]                     DATETIME        CONSTRAINT [DF_TaxQuarterSummary_addedDate_1] DEFAULT (getdate()) NULL,
    [pieId]                         INT             NULL,
    [quarterDate]                   DATE            NULL,
    [grossTaxableIncome]            DECIMAL (18, 2) NULL,
    [bankAccountInterest]           DECIMAL (18, 2) NULL,
    [fdr]                           DECIMAL (18, 2) NULL,
    [taxableIncomeAdjustment]       DECIMAL (18, 2) NULL,
    [fdrAdjustment]                 DECIMAL (18, 2) NULL,
    [fee]                           DECIMAL (18, 2) NULL,
    [tol]                           DECIMAL (18, 2) NULL,
    [fundDeductibleExpenses]        DECIMAL (18, 2) NULL,
    [netIncome]                     DECIMAL (18, 2) NULL,
    [taxPayable]                    DECIMAL (18, 2) NULL,
    [gainZero]                      DECIMAL (18, 2) NULL,
    [gainLow]                       DECIMAL (18, 2) NULL,
    [gainMid]                       DECIMAL (18, 2) NULL,
    [gainHigh]                      DECIMAL (18, 2) NULL,
    [lossZero]                      DECIMAL (18, 2) NULL,
    [lossLow]                       DECIMAL (18, 2) NULL,
    [lossMid]                       DECIMAL (18, 2) NULL,
    [lossHigh]                      DECIMAL (18, 2) NULL,
    [netIncomeAcrossGainsAndLosses] DECIMAL (18, 2) NULL,
    [excessIC]                      DECIMAL (18, 2) NULL,
    [totalFUM]                      DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_TaxQuarterSummary_1] PRIMARY KEY CLUSTERED ([id] ASC)
);

